version: 0.2

phases:
  install:
    commands:
      - echo Install phase started...
      - ls -al
      - python --version
      - aws --version
  pre_build:
    commands:
      - echo Started pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
  
